export enum ActionTypes {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',
  REMOVE_ALERT = 'REMOVE_ALERT',
  SHOW_ALERT = 'SHOW_ALERT',
  ERROR_PROFILE = 'ERROR_PROFILE',
  GET_PROFILE = 'GET_PROFILE',
}
